version: "2"

services:
  frontend:
    image: jberlin/acid-test
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /data/acid20/Archival-Acid-Test-2.0/logsDir:/app/logsDir
    environment:
      - NODE_ENV=production
      - LISTENPORT=8080
      - OUT_SIDE_DOCKER_PORT=8880
      - FRONT_END_DOMAIN=wsdl-docker.cs.odu.edu
      - FRONT_END_LOC=http://wsdl-docker.cs.odu.edu:8080
      - API_ENDPOINT=http://wsdl-docker.cs.odu.edu:8880
    command: node --harmony backend/index.js
  api:
    image: jberlin/acid-test
    restart: always
    ports:
      - "8880:8080"
    volumes:
      - /data/acid20/Archival-Acid-Test-2.0/logsDir:/app/logsDir
    environment:
      - NODE_ENV=production
      - LISTENPORT=8080
      - OUT_SIDE_DOCKER_PORT=8880
      - FRONT_END_DOMAIN=wsdl-docker.cs.odu.edu
      - FRONT_END_LOC=http://wsdl-docker.cs.odu.edu:8080
      - API_ENDPOINT=http://wsdl-docker.cs.odu.edu:8880
    command: node --harmony backend/apiServer.js